package com.yuriisurzhykov.goaldestinator.core.data.cloud

class ServiceNotAvailableException : RuntimeException("Remote service not available!")
